# Generated by Django 5.0.6 on 2024-06-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cart_razor_pay_order_id_cart_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razor_pay_payment_signature',
        ),
    ]
